version: '3'
services:
  ipfs:
    environment:
    - DEBUG=1
    - ipfs_staging=./staging/
    - ipfs_data=./data/
    image: "ipfs/go-ipfs:latest"
    container_name: ipfs
    ports:
     - "5001:5001"
     - "8081:8080"